import {mountCatalogViewers} from './catalog-viewers.js?v=R50';
import {mountFragranceRail} from './fragrance-rail.js?v=R50';
import {mountExperience, mountProduct, mountFeature, disposeScene} from './scene.js?v=R50';
import {products,extras} from './data.js';
const $=s=>document.querySelector(s), main=$('#main'), money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n), names={love:'Love Collection',intimacy:'Intimacy Collection',doppio:'Doppio Respiro'};
const photo=p=>`assets/products/${p.slug}.webp`, img=(p,cls='',eager=false)=>`<img class="${cls}" src="${photo(p)}" alt="${p.name}, flacone Zavyla" loading="${eager?'eager':'lazy'}" width="1000" height="1300">`;
let cart=[];try{cart=JSON.parse(localStorage.getItem('zavyla-bag')||'[]');if(!Array.isArray(cart))cart=[]}catch{};cart=cart.filter(x=>x&&typeof x.id==='string'&&Number.isInteger(x.qty)&&x.qty>0);let filter='all',sort='featured',frame=0,toastTimer;
const card=(p,interactive=false)=>`<article class="product-card reveal"><div class="product-image"><span class="catalog-collection">${names[p.collection]}</span>${interactive?`<div class="catalog-live" data-slug="${p.slug}" data-selected="false" data-atmosphere-weight="1"><span class="catalog-loading">Prepariamo ${p.name}…</span></div><span class="catalog-gesture">Trascina per ruotare</span>`:`<a href="#/profumo/${p.slug}" aria-label="Scopri ${p.name}"><img src="assets/catalog/${p.slug}.jpg?v=R50" alt="${p.name}, flacone con ingredienti e frammenti della pietra del tappo" loading="lazy" width="930" height="1035"></a>`}<button class="quick" data-add="${p.variant}" aria-label="Aggiungi ${p.name} alla bag">+</button></div><a class="product-info" href="#/profumo/${p.slug}"><div><span class="catalog-family">${p.family}</span><h3>${p.name}</h3><p class="catalog-tagline">${p.tagline}</p></div><span class="price">${money(p.price)}</span></a><div class="catalog-card-foot"><span>${p.concentration} · 100 ml</span><a href="#/profumo/${p.slug}">Esplora ↗</a></div></article>`;
const collectionCards=()=>`<div class="collection-grid">${[['love','forgive','Otto emozioni'],['intimacy','silky','Sulla pelle'],['doppio','sylind','Due anime']].map(([c,s,n])=>`<a class="collection-card reveal" href="#/catalogo/${c}"><span class="eyebrow">${n}</span>${img(products.find(p=>p.slug===s))}<div class="card-bottom"><h3>${names[c]}</h3><span>↗</span></div></a>`).join('')}</div>`;
const feature=()=>`<section class="feature"><div class="feature-visual"><div class="inline-three"></div><span class="rotation-hint">TRASCINA IL FLACONE · ← →</span></div><div class="feature-copy reveal"><h2>La pietra.<br>La luce.<br><em>La tua essenza.</em></h2><p>Esplora ogni dettaglio: le venature della pietra, il profilo del vetro, una forma da custodire.</p><a class="text-link" href="#/profumo/forgive">Scopri Forgive ↗</a></div></section>`;
function catalog(c='all'){filter=names[c]?c:'all';return `<section class="page-intro"><span class="eyebrow">IL MONDO OLFATTIVO DI ZAVYLA</span><h1>${names[filter]||'Una fragranza.<br>Mille modi di essere.'}</h1><p>Esplora le nostre creazioni. Lascia che siano le tue emozioni a guidarti.</p></section><section class="catalog-section"><div class="filters"><div class="tabs" aria-label="Filtra per collezione">${[['all','Tutti i profumi'],...Object.entries(names)].map(([k,v])=>`<button data-filter="${k}" class="${filter===k?'active':''}" aria-pressed="${filter===k}">${v}</button>`).join('')}</div><label> <select id="sort" aria-label="Ordina profumi"><option value="featured">Ordine della collezione</option><option value="price">Prezzo crescente</option><option value="name">Nome A–Z</option></select></label></div><div id="catalog-grid" class="product-grid"></div><p class="small" id="result-count"></p></section>`}
let disposeCatalog=()=>{};
function fillCatalog(){disposeCatalog();let list=products.filter(p=>filter==='all'||p.collection===filter);if(sort==='price')list.sort((a,b)=>a.price-b.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));$('#catalog-grid').innerHTML=list.map(p=>card(p,true)).join('');$('#result-count').textContent=`${list.length} fragranze · 100 ml`;observe();disposeCatalog=mountCatalogViewers()}
function detail(p){return `<section class="detail"><div class="detail-art" style="--tint:${p.color}">${img(p,'',true)}</div><div class="detail-copy"><a class="breadcrumb" href="#/catalogo/${p.collection}">← ${names[p.collection]}</a><span class="eyebrow">${p.family}</span><h1>${p.name}</h1><p class="tagline">${p.tagline}</p><p>${p.description}</p><div class="detail-meta"><span>${p.concentration} · 100 ml</span><span>${money(p.price)}</span></div><div class="quantity"><button data-detail-qty="-1" aria-label="Diminuisci quantità">−</button><output id="detail-qty">1</output><button data-detail-qty="1" aria-label="Aumenta quantità">+</button></div><button class="btn" data-add="${p.variant}">${p.preorder?'Preordina':'Aggiungi alla bag'} <span>↗</span></button><p class="small">${p.preorder?'Disponibile in preordine. Tempi da verificare sul sito ufficiale.':'Prezzo IVA inclusa. Disponibilità e spedizione confermate sul sito ufficiale.'}</p><details><summary>Il mondo olfattivo</summary><p>${p.notes.join('<br>')}</p></details><details><summary>Acquisto e assistenza</summary><p>Il checkout prosegue in sicurezza su Zavyla.com, dove potrai verificare disponibilità, consegna e condizioni di acquisto.</p><a class="text-link" href="${p.url}" target="_blank" rel="noopener">Scheda ufficiale ↗</a></details></div></section><section class="section"><h2>La sua scia.</h2><div class="notes">${p.notes.map((n,i)=>`<div class="reveal"><span>0${i+1}</span><h3>${['Il primo incontro','Il cuore','Il ricordo'][i]}</h3><p>${n}</p></div>`).join('')}</div></section><section class="section"><div class="section-head"><h2>Altre affinità.</h2><a class="text-link" href="#/catalogo">Esplora tutte ↗</a></div><div class="product-grid">${products.filter(x=>x.slug!==p.slug&&x.collection===p.collection).slice(0,4).map(p=>card(p)).join('')}</div></section>`}
function gifts(){return `<section class="page-intro"><span class="eyebrow">IL PIACERE DI SCOPRIRE, IL GESTO DI DONARE</span><h1>Un pensiero.<br><em>Infinite emozioni.</em></h1><p>Discovery set, cofanetti e gift card: un invito a entrare nel mondo Zavyla.</p></section><section class="section gift-grid">${extras.map((p,i)=>`<article class="gift-card">${p.image?`<div><img src="${p.image}" alt="${p.name}" loading="lazy"></div>`:''}<h2>${p.name}</h2><p>${['Un primo viaggio tra le fragranze Zavyla.','La Love Collection, da custodire e condividere.','Un ricordo speciale per un giorno da ricordare.','La libertà di scegliere la propria emozione.'][i]||''}</p><label class="small" for="gift-${i}">Scegli un’opzione</label><select id="gift-${i}">${p.variants.map(v=>`<option value="${v.id}">${v.name==='Default Title'?p.name:v.name} · ${money(v.price)}</option>`).join('')}</select><button class="btn" data-gift="${i}">Aggiungi alla bag <span>↗</span></button></article>`).join('')}</section>`}
let disposeRail=()=>{};
let observer;function observe(){observer?.disconnect();observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e))}
function route(){disposeCatalog();disposeCatalog=()=>{};disposeRail();disposeRail=()=>{};disposeScene();document.querySelectorAll('dialog[open]').forEach(d=>d.close());let [page,arg]=(location.hash.startsWith('#/')?location.hash.slice(2):'').split('/');sort='featured';frame=0;if(!page)main.innerHTML=home();else if(page==='catalogo'){main.innerHTML=catalog(arg);fillCatalog()}else if(page==='profumo'){const p=products.find(p=>p.slug===arg);main.innerHTML=p?detail(p):'<section class="section"><h1>Fragranza non trovata.</h1><a href="#/catalogo">Torna ai profumi</a></section>'}else if(page==='collezioni')main.innerHTML=`<section class="page-intro"><span class="eyebrow">LE COLLEZIONI</span><h1>Tre modi di sentire.</h1><p>L’amore, l’intimità, il respiro. Tre universi per dare forma alla tua sensibilità.</p></section><section class="section">${collectionCards()}</section>${feature()}`;else if(page==='maison')main.innerHTML=`<section class="maison-title"><span class="eyebrow">LA MAISON</span><h1>L’arte ci unisce.<br><em>Il profumo ci racconta.</em></h1><p>Roma, 2011. L’incontro tra Victoria e Giancarlo dà inizio a una storia di amore, arte e profumi. Dall’Irlanda e dalla Sardegna arrivano due sensibilità che trovano nell’Italia un linguaggio comune.</p></section>${feature()}<section class="story-strip"><h2>Un nome immaginato.<br>Un sogno condiviso.</h2><div><p>Zavyla è il nome di una terza figlia immaginata: una dedica alla creatività, alla libertà e ai sogni. L’energia dell’arte psichedelica incontra la cura della profumeria artigianale italiana.</p><a class="text-link" href="#/collezioni">Scopri le creazioni ↗</a></div></section>`;else if(page==='regali')main.innerHTML=gifts();else main.innerHTML='<section class="section"><h1>Una strada nuova.</h1><a href="#/">Torna alla home ↗</a></section>';document.title=`${page==='profumo'?(products.find(p=>p.slug===arg)?.name||'Profumi'):({catalogo:'Le fragranze',collezioni:'Le collezioni',maison:'La maison',regali:'Discovery & regali'}[page]||'L’invisibile prende forma')} — Zavyla`;window.scrollTo({top:0,behavior:'instant'});const hv=page?'':homeVariant();document.body.dataset.home=hv;document.body.classList.toggle('immersive-home',!page&&hv!=='pietre');observe();if(!page){mountExperience();disposeRail=mountFragranceRail(products)}else if(page==='profumo'&&products.some(p=>p.slug===arg))mountProduct(arg);else mountFeature()}
function getItem(id){let p=products.find(p=>p.variant===id);if(p)return {id,name:p.name,price:p.price,image:photo(p),url:`#/profumo/${p.slug}`};for(const e of extras){const v=e.variants.find(v=>String(v.id)===id);if(v)return{id,name:e.name+(v.name==='Default Title'?'':` · ${v.name}`),price:Number(v.price),image:e.image,url:'#/regali'}}}
function save(){cart=cart.filter(x=>getItem(x.id)&&x.qty>0&&x.qty<=99);try{localStorage.setItem('zavyla-bag',JSON.stringify(cart))}catch{}$('#count').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function add(id,qty=1){if(!getItem(id))return;const row=cart.find(x=>x.id===id);if(row)row.qty=Math.min(99,row.qty+qty);else cart.push({id,qty});save();$('#toast').textContent=`${getItem(id).name} aggiunto alla bag`;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function renderCart(){save();$('#bag-count').textContent=`(${cart.reduce((s,x)=>s+x.qty,0)})`;$('#cart-body').innerHTML=cart.length?`${cart.map(x=>{const p=getItem(x.id);return `<div class="cart-row">${p.image?`<img src="${p.image}" alt="${p.name}">`:'<span></span>'}<div><a href="${p.url}"><h3>${p.name}</h3></a><div class="quantity"><button data-change="${x.id}" data-delta="-1" aria-label="Diminuisci ${p.name}">−</button><span>${x.qty}</span><button data-change="${x.id}" data-delta="1" aria-label="Aumenta ${p.name}">+</button></div></div><div>${money(p.price*x.qty)}<button class="remove" data-remove="${x.id}">Rimuovi</button></div></div>`}).join('')}<div class="cart-total"><span>Totale</span><span>${money(cart.reduce((s,x)=>s+getItem(x.id).price*x.qty,0))}</span></div><a class="btn checkout" href="https://zavyla.com/cart/${cart.map(x=>`${x.id}:${x.qty}`).join(',')}">Continua su Zavyla.com <span>↗</span></a><p class="small">IVA inclusa. Spese di spedizione e disponibilità verificate al checkout sul sito ufficiale. Il carrello di questa anteprima è salvato solo in questo browser.</p>`:'<p class="empty">La tua bag aspetta una nuova emozione.</p><a class="btn" href="#/catalogo">Esplora le fragranze ↗</a>'}
function search(){const q=$('#query').value.trim().toLocaleLowerCase('it');const matches=products.filter(p=>[p.name,p.family,p.description,...p.notes].join(' ').toLocaleLowerCase('it').includes(q));$('#search-results').innerHTML=matches.length?matches.map(p=>`<a class="search-item" href="#/profumo/${p.slug}">${img(p)}<div><h3>${p.name}</h3><small>${p.family} · ${money(p.price)}</small></div></a>`).join(''):'<p class="empty">Nessuna fragranza trovata. Prova un’altra nota o un nome.</p>'}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-cart')){renderCart();$('#cart').showModal()}if(b.hasAttribute('data-search')){$('#search').showModal();search();$('#query').focus()}if(b.hasAttribute('data-menu'))$('#menu').showModal();if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.add)add(b.dataset.add,b.classList.contains('quick')?1:Number($('#detail-qty')?.value||1));if(b.dataset.gift!==undefined)add($(`#gift-${b.dataset.gift}`).value);if(b.dataset.change){const row=cart.find(x=>x.id===b.dataset.change);row.qty=Math.min(99,row.qty+Number(b.dataset.delta));renderCart()}if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);renderCart()}if(b.dataset.detailQty){const q=$('#detail-qty');q.value=Math.max(1,Math.min(99,Number(q.value)+Number(b.dataset.detailQty)))}if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});fillCatalog()}});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;fillCatalog()}});$('#query').addEventListener('input',search);document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d&&e.clientX<d.getBoundingClientRect().left)d.close()}));document.addEventListener('click',e=>{if(e.target.closest('dialog a'))document.querySelectorAll('dialog[open]').forEach(d=>d.close())});window.addEventListener('hashchange',()=>{if(location.hash&&!location.hash.startsWith('#/'))return;route();main.focus({preventScroll:true})});
document.querySelector('.skip')?.addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'})});
save();

// Tre aperture possibili per la home. Si scelgono con ?home=pietre|materie|atelier
// e la scelta resta per tutta la visita, cosi' si possono confrontare dal vivo.
const HOME_DEFAULT='atelier';
function homeVariant(){
 const q=new URLSearchParams(location.search).get('home');
 if(q){try{sessionStorage.setItem('zavyla-home',q)}catch{}return q}
 try{return sessionStorage.getItem('zavyla-home')||HOME_DEFAULT}catch{return HOME_DEFAULT}
}
const railSection=(titolo)=>`<section class="fragrance-showcase" aria-labelledby="fragrance-showcase-title"><div class="showcase-heading"><h2 id="fragrance-showcase-title">${titolo}</h2></div><div class="fragrance-rail" aria-label="Scegli una delle tredici fragranze">${products.map((p,i)=>`<button class="rail-bottle" data-fragrance-index="${i}" aria-label="Seleziona ${p.name}" aria-pressed="false" tabindex="-1"><span class="rail-placeholder" aria-hidden="true"></span><img class="rail-stone" src="assets/stones/${p.slug}.webp?v=R51" alt="" width="360" height="360" loading="lazy"><span>${p.name}</span></button>`).join('')}</div><div class="rail-navigation"><button data-rail-prev aria-label="Profumo precedente">←</button><span data-rail-count>05 / 13</span><button data-rail-next aria-label="Profumo successivo">→</button></div><div class="rail-information" aria-live="polite" aria-atomic="true"><div class="rail-identity"><span class="eyebrow" data-rail-family></span><h3 data-rail-name></h3></div><div class="rail-story"><p class="rail-tagline" data-rail-description></p><p class="rail-notes" data-rail-notes></p></div><div class="rail-detail"><span data-rail-price></span><a class="text-link" data-rail-link href="#/profumo/give">Esplora la fragranza ↗</a></div></div></section>`;

function home(){
 const v=homeVariant();
 if(v==='pietre')return homePietre();
 if(v==='materie')return homeMaterie();
 return homeAtelier();
}

// A — Le tredici pietre: la collezione e' l'apertura. Si sceglie la pietra,
// il flacone si apre dentro la fila.
function homePietre(){return `<section class="stones-hero" id="experience"><div class="stones-copy"><span class="eyebrow">Tredici pietre, tredici fragranze</span><h1>Scegli<br><em>la tua pietra.</em></h1><p>Ogni tappo è un minerale diverso, scolpito e lucidato uno per uno. Tocca una pietra: il flacone si apre, e con lui la sua storia olfattiva.</p></div>${railSection('Trova la tua affinità.')}</section>${collectionsBand()}${maisonBand()}${closingBand()}`}

// B — Tre materie: un solo flacone, e lo scorrimento racconta pietra, vetro
// ed essenza. Alla fine si apre la fila delle tredici.
function homeMaterie(){return `<section class="experience" id="experience"><div class="experience-stage"><div class="scene-backdrop"></div><div id="scene-host" role="img" aria-label="Dettaglio tridimensionale di pietra, vetro ed essenza: scorri per rivelare il flacone"></div><div class="exp-intro"><span class="eyebrow">L’invisibile, reso indimenticabile.</span><h1>Oltre <br><em>la pelle.</em></h1><div class="intro-bottom"><p>Un incontro tra materia e immaginazione.</p></div></div><ol class="materie" aria-label="Le tre materie"><li><span>La pietra</span><p>Un minerale diverso per ogni fragranza, scolpito a mano.</p></li><li><span>Il vetro</span><p>Parete cava, spessa alla base: la luce ci entra e resta.</p></li><li><span>L’essenza</span><p>Concentrazioni alte, materie prime italiane.</p></li></ol><div class="scene-loading" role="status">Prepariamo il tuo incontro<span></span></div><div class="scene-fallback" hidden><p>La scena 3D non è disponibile su questo dispositivo.</p><a class="text-link" href="#/catalogo">Esplora le fragranze ↗</a></div></div></section>${railSection('Tredici modi di sentire.')}${collectionsBand()}${maisonBand()}${closingBand()}`}

const collectionsBand=()=>`<section class="section"><div class="section-head"><h2>Tre modi di sentire.</h2><a class="text-link" href="#/collezioni">Tutte le collezioni ↗</a></div>${collectionCards()}</section>`;
const maisonBand=()=>`<section class="brand-story" aria-labelledby="brand-story-title"><div class="brand-story-heading"><h2 id="brand-story-title">Due origini.<br>Un incontro.<br><em>Un mondo da sentire.</em></h2></div><div class="brand-story-origin"><span class="brand-place">IRLANDA · SARDEGNA</span><span class="brand-year">2011</span><span class="brand-place">L’INCONTRO, A ROMA</span></div><div class="brand-story-copy"><h3>Prima di un profumo,<br>una storia condivisa.</h3><p>Victoria, irlandese, e Giancarlo, sardo, si incontrano a Roma nel 2011. La passione per l’arte e le fragranze diventa un percorso comune, da cui prende forma Zavyla.</p><p>Il nome è dedicato a una terza figlia immaginata: un sogno di bellezza e libertà. L’ispirazione psichedelica incontra la cura della profumeria artigianale italiana.</p><a class="text-link" href="#/maison">Entra nella nostra storia ↗</a></div><div class="brand-story-foot"><span>Due sensibilità, una visione.</span><span>ARTE · LIBERTÀ · PROFUMERIA ITALIANA</span></div></section>`;
const closingBand=()=>`<section class="discovery"><div><span class="eyebrow">Il primo passo</span><h2>Inizia da un incontro.</h2></div><a class="btn" href="#/regali">Discovery & regali ↗</a></section>`;

function homeAtelier(){return `<section class="experience" id="experience"><div class="experience-stage"><div class="scene-backdrop"></div><div id="scene-host" role="img" aria-label="Dettaglio tridimensionale di pietra, vetro ed essenza: scorri per rivelare il flacone"></div><div class="exp-intro"><span class="eyebrow">L’INVISIBILE, RESO INDIMENTICABILE.</span><h1>Oltre <br><em>la pelle.</em></h1><div class="intro-bottom"><p>Un incontro tra materia e immaginazione.</p><a class="btn-ghost exp-cta" href="#/catalogo">Esplora le fragranze <span>↗</span></a></div></div><div class="scene-loading" role="status">Prepariamo il tuo incontro<span></span></div><div class="scene-fallback" hidden><p>La scena 3D non è disponibile su questo dispositivo.</p><a class="text-link" href="#/catalogo">Esplora le fragranze ↗</a></div></div></section>${railSection('Trova la tua affinità.')}<section class="brand-story" aria-labelledby="brand-story-title"><div class="brand-story-heading"><h2 id="brand-story-title">Due origini.<br>Un incontro.<br><em>Un mondo da sentire.</em></h2></div><div class="brand-story-origin"><span class="brand-place">IRLANDA · SARDEGNA</span><span class="brand-year">2011</span><span class="brand-place">L’INCONTRO, A ROMA</span></div><div class="brand-story-copy"><h3>Prima di un profumo,<br>una storia condivisa.</h3><p>Victoria, irlandese, e Giancarlo, sardo, si incontrano a Roma nel 2011. La passione per l’arte e le fragranze diventa un percorso comune, da cui prende forma Zavyla.</p><p>Il nome è dedicato a una terza figlia immaginata: un sogno di bellezza e libertà. L’ispirazione psichedelica incontra la cura della profumeria artigianale italiana.</p><a class="text-link" href="#/maison">Entra nella nostra storia ↗</a></div><div class="brand-story-foot"><span>Due sensibilità, una visione.</span><span>ARTE · LIBERTÀ · PROFUMERIA ITALIANA</span></div></section><section class="discovery"><div><span class="eyebrow">Il primo passo</span><h2>Inizia da un incontro.</h2></div><a class="btn" href="#/regali">Discovery & regali ↗</a></section>`}
// L'intestazione posa la sua filatura solo quando la pagina si e' mossa.
// Una sentinella alta un pixel invece di un ascoltatore sullo scorrimento:
// niente lavoro a ogni fotogramma.
const sentinel=document.createElement('div');
sentinel.setAttribute('aria-hidden','true');
sentinel.style.cssText='position:absolute;top:0;left:0;width:1px;height:1px;pointer-events:none';
document.body.prepend(sentinel);
new IntersectionObserver(([e])=>document.body.classList.toggle('scrolled',!e.isIntersecting)).observe(sentinel);

route();
